# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Roland < Formula
  desc "AI agent workspace orchestrator"
  homepage "https://github.com/e1sidy/roland"
  version "0.3.1"
  license "MIT"

  depends_on "e1sidy/tap/slate"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/e1sidy/roland/releases/download/v0.3.1/roland_0.3.1_darwin_amd64.tar.gz"
      sha256 "02144732870a3f2db4f3cb0341bf8f87b728fb21663bb86890b6eb66a577413e"

      define_method(:install) do
        bin.install "roland"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/e1sidy/roland/releases/download/v0.3.1/roland_0.3.1_darwin_arm64.tar.gz"
      sha256 "5f9d27db745d28ac9b50e413f89a16693b2ef5593f33a4f5974d6f8a6cd98e87"

      define_method(:install) do
        bin.install "roland"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/e1sidy/roland/releases/download/v0.3.1/roland_0.3.1_linux_amd64.tar.gz"
      sha256 "31c96d573e00c757a71eef47aa1457c6a0fd6f7a57267fe51093169a23146c7d"
      define_method(:install) do
        bin.install "roland"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/e1sidy/roland/releases/download/v0.3.1/roland_0.3.1_linux_arm64.tar.gz"
      sha256 "2e6b3466c268b9cdc8ae69ffe96973d7ab02d97486383b3bb023df201940e27f"
      define_method(:install) do
        bin.install "roland"
      end
    end
  end
end
