# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Roland < Formula
  desc "AI agent workspace orchestrator"
  homepage "https://github.com/e1sidy/roland"
  version "0.3.0"
  license "MIT"

  depends_on "e1sidy/tap/slate"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/e1sidy/roland/releases/download/v0.3.0/roland_0.3.0_darwin_amd64.tar.gz"
      sha256 "53fa388adb8f32bb17d1a5b4042f948b9b1fd14060e5c4fdc7362569added438"

      define_method(:install) do
        bin.install "roland"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/e1sidy/roland/releases/download/v0.3.0/roland_0.3.0_darwin_arm64.tar.gz"
      sha256 "90db454d6ef929517c4817adf7083e33461edebd9b0b200876a7017ed1e69cd0"

      define_method(:install) do
        bin.install "roland"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/e1sidy/roland/releases/download/v0.3.0/roland_0.3.0_linux_amd64.tar.gz"
      sha256 "13a1bc8b5807cd16a7d30258758504d7e79fa40c0643c65f113984d07681a45d"
      define_method(:install) do
        bin.install "roland"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/e1sidy/roland/releases/download/v0.3.0/roland_0.3.0_linux_arm64.tar.gz"
      sha256 "49c6275ed6bb8a904344c0f29a356866061e7d52920d4379d7f65247b2400bc0"
      define_method(:install) do
        bin.install "roland"
      end
    end
  end
end
