# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Roland < Formula
  desc "AI agent workspace orchestrator"
  homepage "https://github.com/e1sidy/roland"
  version "0.2.0"
  license "MIT"

  depends_on "e1sidy/tap/slate"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/e1sidy/roland/releases/download/v0.2.0/roland_0.2.0_darwin_amd64.tar.gz"
      sha256 "4f5de74c50a41418841781bce59caa8a2f7baa94df344ddfde88a8d93e5bfe6d"

      define_method(:install) do
        bin.install "roland"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/e1sidy/roland/releases/download/v0.2.0/roland_0.2.0_darwin_arm64.tar.gz"
      sha256 "a4215272a43bb9be538fd6b64667b89f15d2c2fbf9459dd1ef82c20b94a82485"

      define_method(:install) do
        bin.install "roland"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/e1sidy/roland/releases/download/v0.2.0/roland_0.2.0_linux_amd64.tar.gz"
      sha256 "4e75e710c7c7b6979bbaabc1e0a6a5b1532d5e7c2159921768a6dc6ad6d4dac6"
      define_method(:install) do
        bin.install "roland"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/e1sidy/roland/releases/download/v0.2.0/roland_0.2.0_linux_arm64.tar.gz"
      sha256 "f1a7add846d6f5cd4b15893da862fc01ac7cd02d6141baa8e8f91a988e00a37f"
      define_method(:install) do
        bin.install "roland"
      end
    end
  end
end
