# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Slate < Formula
  desc "Lightweight task management CLI backed by SQLite"
  homepage "https://github.com/e1sidy/slate"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/e1sidy/slate/releases/download/v0.3.0/slate_0.3.0_darwin_amd64.tar.gz"
      sha256 "d11a155b3cb56150e9b8a44b57b7952db74dad68bfa195339f8292e78224c91c"

      define_method(:install) do
        bin.install "slate"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/e1sidy/slate/releases/download/v0.3.0/slate_0.3.0_darwin_arm64.tar.gz"
      sha256 "2bc6f97824cee148a865af394a27f2d7cf8471d0ddb89765d049405c584a60cc"

      define_method(:install) do
        bin.install "slate"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/e1sidy/slate/releases/download/v0.3.0/slate_0.3.0_linux_amd64.tar.gz"
      sha256 "2efa00137794f1add41bba19f466e63058db5a42c415930cdfbd42234042c327"
      define_method(:install) do
        bin.install "slate"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/e1sidy/slate/releases/download/v0.3.0/slate_0.3.0_linux_arm64.tar.gz"
      sha256 "1547eb690347c8bf0fa99a4e537e7a1727d2b73837a4a8b65c5d72b7deb03a69"
      define_method(:install) do
        bin.install "slate"
      end
    end
  end
end
